#! /usr/bin/env perl

system ('jsub',
	'-quiet', 
	'-j', 'y',
	'-N', 'live-scan',
    '-o', '/data/project/checkwiki/var/log',
	'-once',
	'/data/project/checkwiki/bin/live_scan.pl',
    '-c', '/data/project/checkwiki/checkwiki.cfg');


