#! /usr/bin/env perl

system ('jsub',
	'-j', 'y',
	'-N', 'update_html',
	'-o', '/data/project/checkwiki/var/log',
	'-once',
	'/data/project/checkwiki/bin/update_html.pl',
    '-c', '/data/project/checkwiki/checkwiki.cfg',
    '--project', 'all');
